[package]
name = "advent2017"
version = "0.1.0"
authors = ["kazagistar"]

[dependencies]
regex = "0.2"
lazy_static = "1.0.0"
petgraph = "0.4.10"
bit-vec = "0.4.4"
itertools = "0.7.4"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
